# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Assemble the lib"
  lane :assemble do
    gradle(task: "clean assembleRelease")
  end

  desc "Run assemble, lint and tests"
    lane :check do
      gradle(task: "clean assembleDebug")
      gradle(task: "lintDebug ktlintDebugCheck")
      gradle(task: "testDebug")
    end
end
