# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:android)

platform :android do
    OUTPUT_AAR_PATH = "../lib/build/outputs/aar/lib-release.aar"
    CHANGELOG_PATH = '../CHANGELOG.md'

    desc "Run assemble, lint and tests"
    lane :check do
        build(build_type: "debug")
        gradle(tasks: ['lintDebug', 'ktlintDebugCheck', 'testDebug'])
    end

    desc "Release the library"
    lane :release do |options|
        ensure_git_status_clean

        repository_name = ENV['GITHUB_REPOSITORY']
        version_name = ENV['VERSION_NAME']
        changelog_entry = extract_changelog_last_entry

        aar_path = build(build_type: 'release')

        unless ENV['GITHUB_TOKEN']
            UI.user_error("No GITHUB_TOKEN.")
        end
        UI.message(changelog_entry)
        github_release = set_github_release(
          repository_name: 'faberNovel/stateful-layout',
          api_token: ENV['GITHUB_TOKEN'],
          name: "Release #{version_name}",
          tag_name: version_name,
          description: changelog_entry,
          upload_assets: [aar_path]
        )
        puts github_release
    end

    desc "Build the lib"
    private_lane :build do |options|
        build_type = options[:build_type] || 'debug'
        clean = options[:clean] || true
        gradle(task: 'clean') if clean
        gradle(
            task: 'assemble',
            build_type: build_type
        )
        unless File.exist?(OUTPUT_AAR_PATH)
            UI.error("Library wasn't assembled.")
        end
        OUTPUT_AAR_PATH
    end

    desc "Extract last changelog entry"
    private_lane :extract_changelog_last_entry do
        changelog = File.read(CHANGELOG_PATH)
        entries = changelog.split(/^(## .*)$/)
            .drop(1) # drop preambule
            .each_slice(2)
            .map(&:join) # join header with its changes

        entries[1]
    end
end
