name: Test release
on: pull_request
jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    container:
      image: docker://fabernovel/android:api-29-v1.1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ruby cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
        env:
          BASE_BRANCH: ${{ github.base_ref }}
      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle check || bundle install
      - name: Release library
        run: bundle exec fastlane release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_NAME: ${{ github.head_ref }}
