name: Test release
on:
  push:
    branches: master
jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    container:
      image: docker://fabernovel/android:api-29-v1.1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: bundle install
      - name: Launch check
        run: bundle exec fastlane release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
